/**
 * Image pipeline — every captured photo is persisted to document storage
 * (never disposable cache) and processed into variants:
 *   original  → untouched archive copy
 *   report    → ~1800px wide compressed working copy (markup + PDF)
 *   thumbnail → ~500px wide for lists
 *   annotated → flattened markup copy, generated by the markup studio
 */

import * as FileSystem from "expo-file-system/legacy";
import * as ImageManipulator from "expo-image-manipulator";
import { Platform } from "react-native";

import { processPickedPhotoWeb, reencodeWebImage } from "@/lib/filesWeb";

export const PHOTO_DIR = `${FileSystem.documentDirectory ?? ""}photos/`;
export const REPORT_DIR = `${FileSystem.documentDirectory ?? ""}reports/`;
export const BRAND_DIR = `${FileSystem.documentDirectory ?? ""}brand/`;
export const CLOUD_CACHE_DIR = `${FileSystem.documentDirectory ?? ""}cloud-cache/`;

export interface ProcessedPhoto {
  originalUri: string;
  reportUri: string;
  thumbUri: string;
  width: number;
  height: number;
}

/** Idempotent file delete — missing files are fine; other errors are logged. Web: no-op. */
export async function deleteFileQuiet(uri: string | null | undefined): Promise<void> {
  if (!uri || Platform.OS === "web") return;
  try {
    const info = await FileSystem.getInfoAsync(uri);
    if (!info.exists) return;
    await FileSystem.deleteAsync(uri, { idempotent: true });
  } catch (e) {
    const msg = String(e instanceof Error ? e.message : e).toLowerCase();
    if (msg.includes("not found") || msg.includes("no such file") || msg.includes("does not exist")) {
      return;
    }
    console.log("[files] deleteFileQuiet failed", uri, e);
  }
}

/** Delete orig/report/thumb variants for a processed photo. Web: no-op. */
export async function deleteProcessedPhoto(p: ProcessedPhoto): Promise<void> {
  if (Platform.OS === "web") return;
  await deleteFileQuiet(p.originalUri);
  await deleteFileQuiet(p.reportUri);
  await deleteFileQuiet(p.thumbUri);
}

/**
 * True when any asset row still references `uri` on original/report/thumb/annotated.
 * Used before superseding files so duplicated issues that share the same paths are safe.
 */
export function isUriReferencedByAssets(
  assets: readonly {
    originalUri: string;
    reportUri: string;
    thumbUri: string;
    annotatedUri: string | null;
  }[],
  uri: string,
): boolean {
  return assets.some(
    (a) =>
      a.originalUri === uri ||
      a.reportUri === uri ||
      a.thumbUri === uri ||
      a.annotatedUri === uri,
  );
}

/**
 * Delete `uri` only when no asset still references it, and never when it equals
 * `protectOriginalUri` (the archive original must never be removed by supersede).
 */
export async function deleteUriIfUnreferenced(
  uri: string | null | undefined,
  assets: readonly {
    originalUri: string;
    reportUri: string;
    thumbUri: string;
    annotatedUri: string | null;
  }[],
  protectOriginalUri?: string | null,
): Promise<boolean> {
  if (!uri || Platform.OS === "web") return false;
  if (protectOriginalUri && uri === protectOriginalUri) return false;
  if (isUriReferencedByAssets(assets, uri)) return false;
  await deleteFileQuiet(uri);
  return true;
}

/** Options for high-resolution annotated flatten via react-native-view-shot. */
export function annotatedCaptureOptions(width: number, height: number) {
  return {
    format: "jpg" as const,
    quality: 0.9,
    result: "tmpfile" as const,
    width,
    height,
  };
}

async function ensureDir(dir: string): Promise<void> {
  const info = await FileSystem.getInfoAsync(dir);
  if (!info.exists) {
    await FileSystem.makeDirectoryAsync(dir, { intermediates: true });
  }
}

/** Copy a picked/captured photo into persistent storage and build variants. */
export async function processPickedPhoto(
  sourceUri: string,
  id: string,
): Promise<ProcessedPhoto> {
  if (Platform.OS === "web") {
    return processPickedPhotoWeb(sourceUri);
  }

  await ensureDir(PHOTO_DIR);

  const originalUri = `${PHOTO_DIR}orig_${id}.jpg`;
  await FileSystem.copyAsync({ from: sourceUri, to: originalUri });

  const report = await ImageManipulator.manipulateAsync(
    originalUri,
    [{ resize: { width: 1800 } }],
    { compress: 0.72, format: ImageManipulator.SaveFormat.JPEG },
  );
  const reportUri = `${PHOTO_DIR}report_${id}.jpg`;
  await FileSystem.moveAsync({ from: report.uri, to: reportUri });

  const thumb = await ImageManipulator.manipulateAsync(
    reportUri,
    [{ resize: { width: 500 } }],
    { compress: 0.6, format: ImageManipulator.SaveFormat.JPEG },
  );
  const thumbUri = `${PHOTO_DIR}thumb_${id}.jpg`;
  await FileSystem.moveAsync({ from: thumb.uri, to: thumbUri });

  return { originalUri, reportUri, thumbUri, width: report.width, height: report.height };
}

/** Regenerate the small list thumbnail after crop/rotate transforms. */
export async function regenerateThumbnail(uri: string, assetId: string): Promise<string> {
  if (Platform.OS === "web") {
    return (await reencodeWebImage(uri, 500, 0.6)).dataUri;
  }
  await ensureDir(PHOTO_DIR);
  const thumb = await ImageManipulator.manipulateAsync(uri, [{ resize: { width: 500 } }], {
    compress: 0.6,
    format: ImageManipulator.SaveFormat.JPEG,
  });
  const dest = `${PHOTO_DIR}thumb_${assetId}_${Date.now()}.jpg`;
  await FileSystem.moveAsync({ from: thumb.uri, to: dest });
  return dest;
}

/** Persist a flattened annotated capture (from view-shot) for an asset. */
export async function persistAnnotatedCapture(tmpUri: string, assetId: string): Promise<string> {
  if (Platform.OS === "web") return tmpUri;
  await ensureDir(PHOTO_DIR);
  const dest = `${PHOTO_DIR}annotated_${assetId}_${Date.now()}.jpg`;
  await FileSystem.moveAsync({ from: tmpUri, to: dest });
  return dest;
}

export interface TransformedImage {
  uri: string;
  width: number;
  height: number;
}

/** Rotate the report-size working image 90° clockwise. */
export async function rotateWorkingImage(uri: string, assetId: string): Promise<TransformedImage> {
  const result = await ImageManipulator.manipulateAsync(uri, [{ rotate: 90 }], {
    compress: 0.8,
    format: ImageManipulator.SaveFormat.JPEG,
  });
  if (Platform.OS === "web") {
    const durable = await reencodeWebImage(
      result.uri,
      Math.max(result.width, result.height),
      0.8,
    );
    return { uri: durable.dataUri, width: durable.width, height: durable.height };
  }
  const dest = `${PHOTO_DIR}report_${assetId}_${Date.now()}.jpg`;
  await FileSystem.moveAsync({ from: result.uri, to: dest });
  return { uri: dest, width: result.width, height: result.height };
}

/** Crop the report-size working image. Rect is normalised 0..1. */
export async function cropWorkingImage(
  uri: string,
  assetId: string,
  imageWidth: number,
  imageHeight: number,
  rect: { x: number; y: number; width: number; height: number },
): Promise<TransformedImage> {
  const originX = Math.max(0, Math.round(rect.x * imageWidth));
  const originY = Math.max(0, Math.round(rect.y * imageHeight));
  const width = Math.min(imageWidth - originX, Math.round(rect.width * imageWidth));
  const height = Math.min(imageHeight - originY, Math.round(rect.height * imageHeight));
  const result = await ImageManipulator.manipulateAsync(
    uri,
    [{ crop: { originX, originY, width, height } }],
    { compress: 0.8, format: ImageManipulator.SaveFormat.JPEG },
  );
  if (Platform.OS === "web") {
    const durable = await reencodeWebImage(
      result.uri,
      Math.max(result.width, result.height),
      0.8,
    );
    return { uri: durable.dataUri, width: durable.width, height: durable.height };
  }
  const dest = `${PHOTO_DIR}report_${assetId}_${Date.now()}.jpg`;
  await FileSystem.moveAsync({ from: result.uri, to: dest });
  return { uri: dest, width: result.width, height: result.height };
}

/** Persist a picked brand/company logo into document storage (keeps PNG transparency). */
export async function persistBrandLogo(sourceUri: string): Promise<string> {
  if (Platform.OS === "web") return sourceUri;
  await ensureDir(BRAND_DIR);
  const ext = sourceUri.toLowerCase().includes(".png") ? "png" : "jpg";
  const dest = `${BRAND_DIR}logo_${Date.now()}.${ext}`;
  await FileSystem.copyAsync({ from: sourceUri, to: dest });
  return dest;
}

/** Move a generated PDF into persistent report storage. */
export async function persistGeneratedPdf(tmpUri: string, name: string): Promise<string> {
  if (Platform.OS === "web") return tmpUri;
  await ensureDir(REPORT_DIR);
  const safe = name.replace(/[^a-z0-9-_]+/gi, "_").slice(0, 60);
  const dest = `${REPORT_DIR}${safe}_${Date.now()}.pdf`;
  await FileSystem.moveAsync({ from: tmpUri, to: dest });
  return dest;
}

/** Read an image file as a base64 data URI for embedding in report HTML. */
export async function fileToDataUri(uri: string): Promise<string | null> {
  try {
    if (uri.startsWith("http")) return uri;
    if (Platform.OS === "web") return uri;
    const base64 = await FileSystem.readAsStringAsync(uri, {
      encoding: FileSystem.EncodingType.Base64,
    });
    const mime = uri.toLowerCase().endsWith(".png") ? "image/png" : "image/jpeg";
    return `data:${mime};base64,${base64}`;
  } catch (e) {
    console.log("[files] fileToDataUri failed", e);
    return null;
  }
}
