/**
 * Bundled SAMPLE seed photo modules — generated by scripts/generate-seed-photos.mjs.
 */

/* eslint-disable @typescript-eslint/no-require-imports */
export const SEED_COVER = require("../assets/seed/cover.png");
export const SEED_ISSUE_PHOTOS = [
  require("../assets/seed/issue-01-paint.png"),
  require("../assets/seed/issue-02-sealant.png"),
  require("../assets/seed/issue-03-cabling.png"),
  require("../assets/seed/issue-04-door.png"),
  require("../assets/seed/issue-05-membrane.png"),
  require("../assets/seed/issue-06-linemark.png"),
  require("../assets/seed/issue-07-skirting.png"),
  require("../assets/seed/issue-08-switchboard.png"),
] as const;
